# Generated by Django 2.2 on 2021-11-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insect_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('insect_input_img', models.ImageField(upload_to='input_images/')),
                ('insect_detected_img', models.ImageField(blank=True, default=None, upload_to='detected_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
