# Generated by Django 2.2 on 2021-11-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_detection', '0002_auto_20211117_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='insect_images',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='insect_images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insect_images',
            name='name',
            field=models.CharField(blank=True, default='Invalid', max_length=50),
        ),
    ]
