# Generated by Django 2.2 on 2021-11-18 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insect_detection', '0003_auto_20211118_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insect_images',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 18, 3, 14, 33, 93125, tzinfo=utc)),
        ),
    ]
