# Generated by Django 2.2 on 2021-11-18 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insect_detection', '0004_auto_20211118_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insect_images',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 18, 3, 16, 44, 14821, tzinfo=utc)),
        ),
    ]
