# Generated by Django 2.2 on 2021-11-18 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_detection', '0005_auto_20211118_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insect_images',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
