# Generated by Django 2.2 on 2021-11-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insect_detection', '0006_auto_20211118_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insect_images',
            name='name',
        ),
    ]
